### ISSUE TITLE
tr: Illegal byte sequence

### ISSUE THREAD

**Issue by nfurfaro** [aionnetwork/aion#10]
When trying to run the `./generateId.sh script` I get:
`tr: Illegal byte sequence
D----`

For now I found a solution? here:  https://www.real-world-systems.com/docs/tr.1.html

The fix seems to be to run `export LC_ALL=C`

![image](https://user-images.githubusercontent.com/17053076/36045409-da846976-0d92-11e8-97e0-dd395d3ac41a.png)

Host: 
![image](https://user-images.githubusercontent.com/17053076/36048569-debcc754-0d9c-11e8-868b-4a83682cf5e3.png)

VM: ubuntu/xenial64 Vagrant box (16.04)

**Comment by Mactaivsh** [comment]
you are right. same situation.I found an answer here: https://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx

**Comment by mgfield** [comment]
I had the same issue on macOS.  The above fix corrects it.

run: export LC_ALL=C
then run: ./generateId.sh

**Comment by aion-anakha** [comment]
@mgfield gedit is not mandatory, feel free to use any editor to make the necessary changes.
