### ISSUE TITLE
The linux kernel version must great or equal than 4.

### ISSUE THREAD

**Issue by nfurfaro** [aionnetwork/aion#11]
When running ` ./aion.sh -a create`, this message is received:

`Warning! The linux kernel version must great or equal than 4.
exit program.`

I am running Ubuntu v16.04(as recommended) as a vagrant box.

**Comment by aion-jin** [comment]
thanks ufurfaro,   confirmed this is a bug.   in fixing.

**Comment by nfurfaro** [comment]
Great.

**Comment by nfurfaro** [comment]
Sorry my mistake. I wasn't  running the  `./aion.sh -a create` command in my VM, I was running it on my Mac.

**Comment by nfurfaro** [comment]
When I run `./aion.sh -a create` in my ubuntu vm I no longer get an error about the kernal version.

**Comment by 11zeus11** [comment]
Hello i have the same error :echo "Warning! Aion blockchain is fully compatible with the Ubuntu version 16.04. Your current system is older than Ubuntu 16.04. It may has some issues."

But i`m running the last version of ubuntu

**Comment by nfurfaro** [comment]
I had made a stupid mistake. I was trying to run the command in my mac
shell instead of inside the ubuntu vm after accessing through `vagrant
ssh`.
