### ISSUE TITLE
new version 1.2 does not support validateaddress rpc request?

### ISSUE THREAD

**Issue by zzgang** [aionnetwork/aion#1106]
new version 1.2 does not support validateaddress rpc request?

**Comment by AionJayT** [comment]
Hi @zzgang Can you describe it more specific or do you have a link relate with this rpc call, thanks!

**Comment by zzgang** [comment]
rpc works correct  on v 1.0.6, but on v1.2.1 the result is {"code":-32600,"message":"Invalid Request"}

**Comment by AionJayT** [comment]
Sorry for the late reply, The Java kernel didn't change these 2 rpc calls a while. Is it available for you to test with the latest aion pool software?

**Comment by zzgang** [comment]
From V1.1, 
Update tip: Updated RPC library while maintaining legacy support with aion_pool2.

**Comment by zzgang** [comment]
getblocktemplate somtimes returns : 
response: { code: -1, message: 'no mining block template ' }
