### ISSUE TITLE
LevelDB / sync freeze

### ISSUE THREAD

**Issue by equ1miner** [aionnetwork/aion#1115]
We use java for payments without mining on this wallet.
We are getting an issue that the blockchain stopped syncing with some corruption.
After reverting several blocks we still don't have full sync to allow payments.

A full database check is being run to hopefully correct the corruption!

Please check the stability of this kernal.  I have encountered this once before and had to sync fresh from block 0

## System Information

I'm running:

- **Which Aion version?**: 0.2.x.{git-revision}
oan-v1.3.5635040d9-2020-02-09.tar.bz2

- **Which operating system?**: Linux
- **Which distributor and version?**: Ubuntu 18
- **How installed?**: from source
- **Are you fully synchronized?**: no 
- **Did you try to restart the node?**: yes

**Comment by zzgang** [comment]
20-03-02 14:37:30.406 ERROR SYNC [p2p-worker-0]: RLP decode error!
org.iq80.leveldb.DBException: Corruption: block checksum mismatch

how to correct this?

**Comment by AionJayT** [comment]
@equ1miner @zzgang  Hi, the Java kernel has been switched the default DB to rocksDB, have you tested with the new Java kernel release?
