### ISSUE TITLE
dynmic generated node id need pesist to config file after first boot.

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#115]
now every fresh boot will change the node id if deployment not set it to a fixed id.  it will blow up in all nodes cache, same ip:port have multiple entry.

eg:

![image](https://user-images.githubusercontent.com/35697444/36998160-fc3ae40a-2089-11e8-9e3b-b9c5035043af.png)

**Comment by aion-6368726973** [comment]
patched at a151ebc4e04593bf28eaab2fb36a8d9bc89719db
