### ISSUE TITLE
Setting public IP in config prevents syncing

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion#123]
I did this for the first time, when updating to 0.1.14 (from the [docs](https://github.com/aionnetwork/aion/wiki/Aion-Network-Configuration))

>Note: To allow peers to connect to you, you must also change your configuration IP from 127.0.0.1 to a public IP on your machine. If you are unsure about having a public IP, set it to 0.0.0.0.

So I added my public ip, but the kernel wouldn't sync at all anymore. I'd reverted to a previous block a couple of times, didn't help. Then I changed the ip back to 127.0.0.1 and it started syncing immediately.

Maybe I didn't understand the docs correctly, or maybe this is a bug?

**Comment by alexander-vi** [comment]
+1 Had the same issue. I use server with dedicated ip and internal miner. And the same, reverting to 127.0.0.1 helped to sync.

**Comment by gonuco** [comment]
sorry , the docs is confusing.   
1. if you directly connected to internet,  the public IP is your NIC ( network interface card ) IP. then you can set it .
2. if you are inside a LAN and using NAT to access internet,  ( most home user situation),  you need bind your config to you NIC ip. ( nic ip can be found from "ifconfig"  or from your gnome system settings.
3. if you have multiple NIC,  use "0.0.0.0" will bind aion p2p module to all your NIC.

**Comment by aion-anakha** [comment]
The [doc](https://github.com/aionnetwork/aion/wiki/Aion-Network-Configuration) has been updated. As @JimVanEeden and @alexander-vi mentioned, in order for syncing to work, the config should not be set with a public IP.
