### ISSUE TITLE
Request: ID Generation Option in CLI

### ISSUE THREAD

**Issue by aion-kimcodeashian** [aionnetwork/aion#133]

**Comment by gonuco** [comment]
you mean network id right ? 
the tools is in script/generateId.sh

**Comment by aion-kimcodeashian** [comment]
The issue is that there are two different Regexes, (generator regex out of sync with validating regex), so nodeIds genereated by the script fail validation in the kernel:
```
PATTERN_P2P.matcher(_p2p).matches())
```
It's bad practice (imho) to have the same logic repeated in two different places.
If we implement generateNodeId as a CLI arg, that gets passed to jvm, we can have only one place where the nodeId format is defined, so we don't have to upgrade logic in two different places. 
For reference, in the kernel, the regex for the nodeId is:
```
REGEX_NODE_ID = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
```
In the script (generateId.sh), the generator generates with caps: 
```
random-string() {
   cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 
}
${text:0:8}-${text:8:4}-${text:12:4}-${text:16:4}-${text:16:12}
```

**Comment by aion-6368726973** [comment]
dev branch -> aion.sh -c will generate new id without losing existing seed nodes setting. 
patch on a151ebc4e04593bf28eaab2fb36a8d9bc89719db

**Comment by ali-sharif** [comment]
`aion.sh -c` has the effect of overriding everything else in the config, which is not the intended behaviour. 

Ideally, one of the following will be a good resolution: 
1. CLI option that just generates a nodeId
2. 'config file update' functionality that just touches the nodeId to update it.
