### ISSUE TITLE
new added peers.xml slow down kernel boot time.

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#136]

**Comment by RobertSynapsics** [comment]
I'll do some timings and see if it's the xml format to blame

**Comment by JayT106** [comment]
running dev branch build rev 461289e, got this error

also, the node can not connect to the seeding node.

18-03-07 09:34:20.922 INFO  GEN  [main]: loaded block <num=152, root=fc6efa8f... l=32>
<error on-parsing-peers-xml msg=/home/jay/workspaceAion/aiontest/aion/pack/aion/config/peers.xml (No such file or directory)>
18-03-07 09:34:20.996 INFO  GEN  [main]: <node-started endpoint=p2p://ca220a93-9596-4906-8fc7-55b4e360af7e@127.0.0.1:30303>
18-03-07 09:34:20.999 INFO  CONS [main]: <delayed-start-sealing>
^C18-03-07 09:34:22.511 INFO  GEN  [Shutdown]: Starting shutdown process...
18-03-07 09:34:22.512 INFO  GEN  [Shutdown]: Shutting down zmq ProtocolProcessor
18-03-07 09:34:25.512 INFO  GEN  [Shutdown]: Shutdown zmq ProtocolProcessor... Done!
18-03-07 09:34:25.513 INFO  GEN  [Shutdown]: Shutting down sealer
18-03-07 09:34:25.513 INFO  GEN  [Shutdown]: Shutdown sealer... Done!
18-03-07 09:34:25.513 INFO  GEN  [Shutdown]: Shutting down the AionHub...
18-03-07 09:34:25.513 INFO  GEN  [Shutdown]: <KERNEL SHUTDOWN SEQUENCE>
18-03-07 09:34:25.513 INFO  GEN  [Shutdown]: <shutdown-sync-mgr>
18-03-07 09:34:25.515 INFO  GEN  [Shutdown]: <shutdown-p2p-mgr>
18-03-07 09:34:25.516 INFO  GEN  [Shutdown]: TransactionExecThread shutting down...
18-03-07 09:34:25.516 INFO  GEN  [Shutdown]: TransactionExecThread waiting termination.
18-03-07 09:34:25.517 INFO  GEN  [Shutdown]: TransactionExecThread shutdown... Finished!
18-03-07 09:34:25.517 INFO  GEN  [Shutdown]: <shutdown-tx>

**Comment by RobertSynapsics** [comment]
Could you confirm that if you change the default port of the p2p module this still happens? Because for me the startup process hangs for the default port but if i change it works and starts syncing
