### ISSUE TITLE
JSON RPC Enhancement - new functions

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion#151]
I'll use this as staging for method requests for either:

1. unimplemented functions documented in [standard spec](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3js-api-reference)
2. [functions geth exposes as managment extensions](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#list-of-management-apis)
3. any new function requests

**Comment by yao-sun** [comment]
Hey I'd like to request the following: ``getPendingTransactions()``, getTransactionStatus(bytes32 transactionHash), ``getBlock('pending')``

### getPendingTransactions()

This method should expose a list of transactions that are currently in the ``pending`` pool. In addition to the regular fields associated with transactions, I'd like to add fields to give information on:

* The source of the transaction, was it local or remote?
* The timestamp at which we received the transaction
* The timestamp that the transaction was signed at (Im not sure if this is already exposed in ``getTransaction``)

### getTransactionStatus(bytes32 transactionHash)

(This is just a thought!)
Currently, we query transaction status based on a number of factors, for example:

* Does the transaction return a blockHash?
* Does the receipt exist?
* Is the status of the receipt 0x1?

It would be nice to reduce this down to a form of errcodes or enums, for example:

~~~~
enum TransactionStatus {
    UNSEEN,
    DROPPED,
    PENDING,
    CONFIRMED
}
~~~~

The thought process here is to rigorously define certain "stages" the transactions go through. Thereby removing any ambiguity on what the user has to query.


### getBlock('pending')

Not sure if we have this yet, but this would be similar or same as ``eth.getBlock('pending')``, which retrieves the pending block (the block we're currently mining on).

**Comment by jonathanjm** [comment]
Hi! I'd like to request these functions: version.* methods, isConnected(), reset(), gasPrice and getGasPrice(<callback>), getHashrate(<callback>), getMining(<callback>) and getBlockTransactionCount(hashStringOrBlockNumber, <callback>).

We're building a network manager that tracks the network status of AION.

**Comment by ali-sharif** [comment]
Acknowledged @jonathanjm.

**Comment by ali-sharif** [comment]
@jonathanjm I'm almost done implementing the remaining web3 functions. Running through tests and bugfixing now. I'm batching up all the changes and will hopefully be able to get the PR before the end of the week (... hopefully). After this, we should be pretty close to covered on json-rpc spec (will post something on the Wiki documenting rpc coverage and deviations from the spec.

**Comment by jonathanjm** [comment]
@ali-sharif thanks! I'll keep an eye on the releases page.

**Comment by jonathanjm** [comment]
Hi @ali-sharif, think you'll have this ready today?

**Comment by ali-sharif** [comment]
@jonathanjm - I ended up refactoring the whole web3 server-side library (minus the NIO server implementation) and got spec compliance with the ethereum spec up to 100% in most places (the only thing that's left is pending pool integration, which is undergoing some structural changes atm so we'll leave that for later). I'm just writing tests to gurantee minimal regression, although some regression is to be expected. I can get you a build off my branch as early as Monday morning! Sorry for the delay, there were more peripheripheral components that needed to be built than expected, in order to service some of the new API endpoints.

**Comment by jonathanjm** [comment]
@ali-sharif thanks for the update, Monday morning sounds good. If you guys need any extra help now or in the future let me know, I'm happy to help.

**Comment by ali-sharif** [comment]
I reached out to you over email with the binary.

**Comment by AionJayT** [comment]
confirmed the issue fixed with @ali-sharif. close issue
