### ISSUE TITLE
It's stuck on Block #327056

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion#154]
It has been hanging on the same block for about 4 hours now.

https://dashboard.aion.network/#/dashboard

**Comment by JimVanEeden** [comment]
This might be a dashboard problem by the way.

**Comment by Xiaoyang-Zhu** [comment]
yeah. the aion core is running smoothly. it's just the dashboard problem.

**Comment by ali-sharif** [comment]
Thanks for reporting! Dashboard data-provider server got stuck. Fixed.
