### ISSUE TITLE
The new 0.15 version of the aion core can encounter some previous add transaction errors

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [aionnetwork/aion#163]
18-03-10 02:21:37.426 INFO  CONS [sync-import]: branching: from = 332422/05ac34fac2732e7ff481db24621ac1b403463c01ef5d6ecfeaab24410177a71b, to = 332423/711ac6c5a02e50ed2c10a6821efa05db7b9a046d945ef33406bf85b11348db4b
18-03-10 02:21:37.442 INFO  SYNC [sync-import]: <import-best num=332423 hash=711ac6 txs=0>
18-03-10 02:21:39.531 INFO  SYNC [sync-import]: <import-best num=332424 hash=f958ba txs=0>
18-03-10 02:21:42.766 ERROR SYNC [p2p-write]: <res-bodies invalid>
18-03-10 02:26:45.856 INFO  CONS [rpc-server]: branching: from = 332449/d8732e521c0bbf1b20ebcfeb9377e5fffb3a5c128bc3410d205be7cb181604c5, to = 332449/705ae04cd24eaf882b4f1a198c055c3f14d6a30c6e88d5533b885c9e6c66fc23
18-03-10 02:26:52.350 ERROR GEN  [p2p-write]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-10 02:26:53.876 ERROR GEN  [p2p-write]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-10 02:26:56.480 ERROR GEN  [p2p-write]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-10 02:26:59.266 ERROR GEN  [p2p-write]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-10 02:27:01.774 ERROR GEN  [p2p-write]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE

**Comment by AionJayT** [comment]
Hi Xiaoyang-Zhu, Thanks for reporting these issue. We have a PR solve the tx propagation issue. see [https://github.com/aionnetwork/aion/pull/162](url). Next build should fix the issue.

**Comment by Xiaoyang-Zhu** [comment]
I also have a question for you. Do we need to change to the old version 0.14 of aion core or just use the 0.15?

**Comment by AionJayT** [comment]
0.1.15 fixed some critical bugs also improved the network module stability. I recommend you to upgrade the core to the latest version.  you should be able to move the database folder to the new binary folder. Therefore, you don't need to take too much time to fully sync to the best block

**Comment by Xiaoyang-Zhu** [comment]
yeah, thanks for your suggestion. That's what I've done with the database migration. 

It looks the dashboard didn't show the new aion core mining information. you guys also need to update the dashboard, right?

**Comment by AionJayT** [comment]
Yes, the dashboard core might not have been updated to the latest core version yet. Please give us some time to update the core. Thanks.

**Comment by Xiaoyang-Zhu** [comment]
ha ha, no problem, I just want to confirm it. love you guys.
