### ISSUE TITLE
Sending transactions using Java API

### ISSUE THREAD

**Issue by aion-anakha** [aionnetwork/aion#180]
When sending continuous transactions using the Java API, the transactions are being sealed in the blocks on the kernel side, however there are three main error outputs showing up on the API side: 

![output1](https://user-images.githubusercontent.com/36010590/37405303-b435c66a-276a-11e8-883f-677ea85608c3.png)

![output2](https://user-images.githubusercontent.com/36010590/37405305-b7181c3e-276a-11e8-9a40-02c1e0a33147.png)

![output3](https://user-images.githubusercontent.com/36010590/37405308-b936481a-276a-11e8-8273-6271a3f9f2be.png)

**Comment by JayT106** [comment]
Did you send the transactions to the testnet? if yes, currently the running kernel of the testnet has some bugs. If you see this message. means the api message timeout. cause the kernel didn't give a response.

**Comment by aion-anakha** [comment]
When looking back at the output, after 180 account creations, some transactions go through, but majority fail and return an invalid transaction hash. This is related to the above errors as well.

**Comment by AionJayT** [comment]
Close the issue
