### ISSUE TITLE
After  INVALID_NRG_LIMIT error,  it that account resend any other tx , will get an INVALID_NONCE eror

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#204]
18-03-16 14:46:49.073 DEBUG TX   [pool-5-thread-5]: NonceMgr - getNonceAndAdd: ADDR [79e4617580218147d4808bcc93c086961812b4b9458d33a9a5828f1504cb0c5c] REPO [2896] NM [3832] POOL [3830] 
18-03-16 14:46:49.073 DEBUG TX   [TransactionExecThread]: TransactionExecThread.submitTransaction: TransactionData [hash=, nonce=3831, receiveAddress=7a181333fe5644cbc6e00ff3dee000e0634b4c87e971e4e64aaf47edb4e3d758, value=0, data=10462fd000000000000000000000000000000001, timeStamp=1521226009073486, Nrg=20000, NrgPrice=1, txType=1, sig=org.aion.crypto.ed25519.Ed25519Signature@7fa75f00]
18-03-16 14:46:49.074 ERROR GEN  [TransactionExecThread]: addPendingTransactionImpl tx is rejected due to: INVALID_NRG_LIMIT
     and then
   .
   .
   .
   v

8-03-16 14:47:48.162 DEBUG TX   [pool-5-thread-4]: NonceMgr - getNonceAndAdd: ADDR [79e4617580218147d4808bcc93c086961812b4b9458d33a9a5828f1504cb0c5c] REPO [2896] NM [3832] POOL [3830] 
18-03-16 14:47:48.162 DEBUG TX   [TransactionExecThread]: TransactionExecThread.submitTransaction: TransactionData [hash=, nonce=3831, receiveAddress=7a181333fe5644cbc6e00ff3dee000e0634b4c87e971e4e64aaf47edb4e3d758, value=0, data=10462fd000000000000000000000000000000001, timeStamp=1521226068162530, Nrg=100000, NrgPrice=1, txType=1, sig=org.aion.crypto.ed25519.Ed25519Signature@58dce3a1]
18-03-16 14:47:48.163 ERROR GEN  [TransactionExecThread]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE

**Comment by AionJayT** [comment]
NonceMgr has been removed. refactored the AionPendingStateImpl a lot. Close this issue
