### ISSUE TITLE
16G ram , kernel still crash.  more than 10K thread eat all system resource.

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#208]
![image](https://user-images.githubusercontent.com/35697444/37550154-fd60512a-295e-11e8-8947-9632e4b99f06.png)

spawned too many p2p-thread.....

**Comment by aion-jin** [comment]
![image](https://user-images.githubusercontent.com/35697444/37550169-3856f5d6-295f-11e8-9c4c-c02878e14639.png)

**Comment by aion-6368726973** [comment]
Limited.
