### ISSUE TITLE
balance not being imported

### ISSUE THREAD

**Issue by asebak** [aionnetwork/aion#21]
Refer to this issue I reported here:

https://forum.aion.network/t/new-kernel-version-account-missing/218/6

Not sure if this was fixed but whenever you import an account to a new kernel the balance is not transferring over.

**Comment by JimVanEeden** [comment]
I just updated to the new kernel version (from 0.1.10 to 0.1.11) and copied the database and exported the accounts from the old version and imported to the new version. My balances were all still there this time.
