### ISSUE TITLE
if node get invalid nonce, will stop tx broadcast...   

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#211]
![image](https://user-images.githubusercontent.com/35697444/37551435-c92af33a-2975-11e8-8c9b-a2a62e7171f8.png)

**Comment by aion-jin** [comment]
the node also stopped sync any new block and stuck. 

Question here is:
Should kernel pause broadcast Tx after sync paused ?

**Comment by AionJayT** [comment]
close issue.
