### ISSUE TITLE
update to 0.1.16 imcompatible with mining solo pool

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [aionnetwork/aion#217]
I just updated the new released core, but when the miners found a block.   the solo mining pool occurs 

2018-03-18 16:13:30 [Pool]	[aion] (Thread 1) rpc error with daemon instance 0 when submitting block with submitblock {"type":"request error","message":"socket hang up"}

**Comment by AionJayT** [comment]
Hi Yang,
Did you use the release miner and pool? if yes, sorry for let you has a bad experience.
We modified and enhanced the miner a little bit during this week and we haven't update the miner/pool binary . So please build your own binary using the latest dev branch for testing.

**Comment by Xiaoyang-Zhu** [comment]
OK. Got it. Thanks.

**Comment by aion-Ross** [comment]
The latest release (v0.1.10) is up on the aion_miner repo. It should solve the compatibility issues with the new kernel release. 

https://github.com/aionnetwork/aion_miner/releases/tag/v0.1.10

**Comment by Xiaoyang-Zhu** [comment]
tested! it works. Thanks.
