### ISSUE TITLE
Updating of wiki

### ISSUE THREAD

**Issue by johnlim** [aionnetwork/aion#22]
Hi,

May I know what's the preferred way to issue "change requests" for the wiki? As I am unable to edit or issue a PR for the wiki, is there a better way to suggest changes to the wiki other than opening up an issue?

In https://github.com/aionnetwork/aion/wiki/Internal-Miner, under ```miner-address: the wallet address that will collect AION for mining blocks``` I'd like to make a suggestion to add the following information "To create a new wallet, run `./aion.sh -a create`. To import an existing wallet, please refer to `https://github.com/aionnetwork/aion/wiki/Importing-Accounts`"

Cheers,
John

**Comment by aion-anakha** [comment]
Thank you for the edit suggestion! I have made the change you have suggested above. Currently there is no alternate way to issue change requests for wikis, however I have created a new label for specifying any wiki changes in the future.
