### ISSUE TITLE
google local cache use 23% heap,  are there any other way to be more memory efficient? 

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#220]
![image](https://user-images.githubusercontent.com/35697444/37568289-9712ec1a-2aa9-11e8-80f2-66905856def7.png)

**Comment by AlexandraRoatis** [comment]
The use of the heap cache can be disabled completely by adding in the database config the following line:
```
<enable_heap_cache>false</enable_heap_cache>
```
Alternatively, the number of entries kept in memory can be limited using:
```
<enable_heap_cache>true</enable_heap_cache>
<max_heap_cache_size>200</max_heap_cache_size>
```
Further, if you enable the cache statistics with the line below, and debug messages on the database, you can view how well the cache is doing and updated the size in the config based on the desired performance and what the specific machine can handle.
```
<enable_heap_cache_stats>true</enable_heap_cache_stats>
```

**Comment by aion-jin** [comment]
could you recheck if our default settings will cover most scenario ? ( default to 8G-16G memory range.) after that , please close this ticket.
