### ISSUE TITLE
aion.sh -r    passed , but DB have missing parent block issue.

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#224]
need review -r  process.

**Comment by AlexandraRoatis** [comment]
The pruning using -r checks for missing blocks from the main chain. A message like the following will be returned:
```
18-03-19 19:19:15.775 INFO  DB   [main]: Pruning side chains on level 290607.
18-03-19 19:19:15.776 INFO  DB   [main]: Pruning side chains on level 290606.
18-03-19 19:19:15.777 INFO  DB   [main]: Pruning side chains on level 290605.
18-03-19 19:19:15.779 ERROR DB   [main]: Block #290604 missing from the database. Cannot proceed with block pruning and total difficulty updates.
```
I can confirm the output above was given for version [0.1.16.5fc4acb](https://github.com/aionnetwork/aion/tree/5fc4acbeeda8e42ee920c952137a197d162ef0a9).
The missing parent issue will not appear if the block is on the main chain.
