### ISSUE TITLE
JVM Core Dump

### ISSUE THREAD

**Issue by Crypto-Cow** [aionnetwork/aion#232]
Hello,
During the weekend I attempted to run the kernel while you (the dev team) were running the network stress tests. I could run 0.1.15 with no issues, but when I switched to 0.1.16 I ended up getting some JVM core dumps. After the second core dump I stopped running the kernel, it's up now and seems to be fine. 

Attached are the error and replay files.

[hs_err_pid10607.log](https://github.com/aionnetwork/aion/files/1825475/hs_err_pid10607.log)
[hs_err_pid11493.log](https://github.com/aionnetwork/aion/files/1825476/hs_err_pid11493.log)
[kernel-output-pid10607.txt](https://github.com/aionnetwork/aion/files/1825477/kernel-output-pid10607.txt)
[replay_pid10607.log](https://github.com/aionnetwork/aion/files/1825479/replay_pid10607.log)
[replay_pid11493.log](https://github.com/aionnetwork/aion/files/1825480/replay_pid11493.log)

My system (bare metal): i7, 32G ram, 250G ssd, 1080TI.

**Comment by gonuco** [comment]
seems it's jvm hot compile crash. we don't know root reason yet from the log file. will keep watching on those issues .

**Comment by Crypto-Cow** [comment]
Is there anything else I can do to assist?  Any additional logging I can turn up and run until it dumps again?

**Comment by JimVanEeden** [comment]
I had the same problem after letting it run overnight

[hs_err_pid29401.log](https://github.com/aionnetwork/aion/files/1858894/hs_err_pid29401.log)

**Comment by JimVanEeden** [comment]
I've had this problem 3 mornings in a row now. When I let it run overnight it always crashes like this.

**Comment by Crypto-Cow** [comment]
Just had my first core dump with v0.2.1 :(
[hs_err_pid13278.log](https://github.com/aionnetwork/aion/files/1904998/hs_err_pid13278.log)
[replay_pid13278.log](https://github.com/aionnetwork/aion/files/1904999/replay_pid13278.log)

**Comment by qoire** [comment]
Closing, issues experienced in v0.2.1 are no longer relevant.
