### ISSUE TITLE
Stops syncing after ERROR SYNC

### ISSUE THREAD

**Issue by saaperezru** [aionnetwork/aion#24]
The kernel seems to stop syncing after the following log shows up:

`ERROR SYNC [pool-3-thread-7]: <res-headers decode-msg msg-bytes=268969 from-node=-39373317 >   `

**Comment by aion-jin** [comment]
was you running the latest binary ?  version v0.1.11 ?

**Comment by saaperezru** [comment]
Yes

**Comment by AionJayT** [comment]
no issue after version 0.2.x. close issue.
