### ISSUE TITLE
New version 0.1.17

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [aionnetwork/aion#267]
I run the new release version about 20 miniutes, then i got the error

18-03-23 23:10:59.060 ERROR GEN  [ForkJoinPool-3-worker-7]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:11:19.593 ERROR GEN  [ForkJoinPool-3-worker-1]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:11:48.752 ERROR GEN  [ForkJoinPool-3-worker-0]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:11:48.843 ERROR GEN  [p2p-worker-4]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:11:48.854 ERROR GEN  [p2p-worker-4]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:11:48.861 ERROR GEN  [p2p-worker-4]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:11:48.863 ERROR GEN  [p2p-worker-4]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:11:48.865 ERROR GEN  [p2p-worker-4]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE
18-03-23 23:12:09.502 ERROR GEN  [ForkJoinPool-3-worker-3]: addPendingTransactionImpl tx is rejected due to: INVALID_NONCE

**Comment by AionJayT** [comment]
Thanks for the report, we are working on it. we are doing some pressure test when you running the kernel.
It won't effect the mining. we wil fix it as soon as possible

**Comment by Xiaoyang-Zhu** [comment]
glad to hear that, thanks
