### ISSUE TITLE
block import to heavy cause the sync slow done

### ISSUE THREAD

**Issue by JayT106** [aionnetwork/aion#268]
18-03-24 16:05:55.904 INFO  SYNC [sync-ib]: <import-status: node = 011dae, number = 440624, txs = 448, result = EXIST, time elapsed = 57 ms>
18-03-24 16:05:55.954 INFO  SYNC [sync-ib]: <import-status: node = 011dae, number = 440625, txs = 448, result = EXIST, time elapsed = 49 ms>
18-03-24 16:06:12.840 INFO  SYNC [sync-ib]: <import-status: node = 011dae, number = 440626, txs = 448, result = IMPORTED_BEST, time elapsed = 16886 ms>
18-03-24 16:06:12.840 INFO  SYNC [sync-ib]: <import-status: node = 011dae, number = 440626, txs = 448, result = IMPORTED_BEST, time elapsed = 16886 ms>
18-03-24 16:06:29.192 INFO  SYNC [sync-ib]: <import-status: node = 011dae, number = 440627, txs = 448, result = IMPORTED_BEST, time elapsed = 16351 ms>

**Comment by AionJayT** [comment]
after DB turned-up. it works well. close ticket.
