### ISSUE TITLE
Yao's benchmark not able run with latest dev.

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#277]
![image](https://user-images.githubusercontent.com/35697444/37882474-98e5b1e4-3071-11e8-8a3b-d641b118376d.png)

**Comment by qoire** [comment]
The underlying JSON structure was changed for some events, I believe a fix has already been implemented, we will present an updated binary and merge the code tomorrow.

**Comment by AionJayT** [comment]
confirmed with yao. close issue.
