### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by NoahMarconi** [aionnetwork/aion#28]
Hi, what's the minimum machine size? I'm getting a not enough space error:

```
root@aion:~/aion# ./aion.sh -a list
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 2147483648, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /root/aion/hs_err_pid24522.log
```

I'm currently testing on a Digital Ocean droplet with these basic specs: 4 GB Memory / 25 GB Disk / TOR1 - Ubuntu 16.04.3 x64

**Comment by jzaluski** [comment]
I think this error has to do with harddrive space on your (I assume) VM

This video helped me
https://www.youtube.com/watch?v=7Aqx-VHv2_k

**Comment by aion-jin** [comment]
Aion recommend use 8G memory with 10G disk space.   If only 4G memory available,  you can try turnoff mining and lower the number of peer connections.
Your error is the disk full,   you can try cleanup your diskspace by 'apt-get  autoremove'  etc.

**Comment by NoahMarconi** [comment]
Bumping up the memory seemed to fix it. Seems odd that the disk full error is appearing; the machine has 2.5x the recommended disk space.
