### ISSUE TITLE
LevelDB Configurations Change

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion#289]
Since we're currently tuning parameters, if you find a good parameter setting, note it down in this ticket with a small log (for example sync size).

**Comment by yulongaion** [comment]
Found a decent configuration, average import time `2 seconds` for the 465 txs blocks:
```xml
<db>
    <path>database</path>
    <vendor>leveldb</vendor>
    <enable_heap_cache>false</enable_heap_cache>
    <max_heap_cache_size>1024</max_heap_cache_size>
    <enable_db_cache>true</enable_db_cache>
    <enable_db_compression>false</enable_db_compression>
    <max_fd_alloc_size>128</max_fd_alloc_size>
    <block_size>16mB</block_size>
    <write_buffer_size>64mB</write_buffer_size>
    <cache_size>256mB</cache_size>
</db>
```

**Comment by alexander-vi** [comment]
I've got about 2x boost.

Before:
```
18-03-27 17:40:52.801 INFO  SYNC [sync-ib]: <import-status: node = 222625, number = 460415, txs = 467, result = IMPORTED_BEST, time elapsed = 4732 ms>
18-03-27 17:40:55.242 ERROR SYNC [p2p-worker-8]: <assemble-and-validate-blocks node=222625>
18-03-27 17:40:57.288 INFO  SYNC [sync-ib]: <import-status: node = 222625, number = 460416, txs = 467, result = IMPORTED_BEST, time elapsed = 4487 ms>
```

After:
```
18-03-27 17:56:22.646 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460635, txs = 284, result = IMPORTED_BEST, time elapsed = 2491 ms>
18-03-27 17:56:25.518 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460636, txs = 467, result = IMPORTED_BEST, time elapsed = 2871 ms>
18-03-27 17:56:28.349 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460637, txs = 467, result = IMPORTED_BEST, time elapsed = 2831 ms>
```

**Comment by gilby125** [comment]
I have seen similar  2x  results:
 
`18-03-27 13:11:42.111 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460429, txs = 467, result = EXIST, time elapsed = 1 ms>
18-03-27 13:11:44.242 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460445, txs = 465, result = IMPORTED_BEST, time elapsed = 1274 ms>
18-03-27 13:11:45.370 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460446, txs = 467, result = IMPORTED_BEST, time elapsed = 1128 ms>
18-03-27 13:11:48.082 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460449, txs = 467, result = IMPORTED_BEST, time elapsed = 1277 ms>
18-03-27 13:11:49.456 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460450, txs = 427, result = IMPORTED_BEST, time elapsed = 1373 ms>
18-03-27 13:11:52.222 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460453, txs = 467, result = IMPORTED_BEST, time elapsed = 1163 ms>
18-03-27 13:11:53.191 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460454, txs = 425, result = IMPORTED_BEST, time elapsed = 969 ms>
18-03-27 13:11:54.802 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460456, txs = 467, result = IMPORTED_BEST, time elapsed = 1086 ms>
18-03-27 13:12:07.158 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460464, txs = 467, result = IMPORTED_BEST, time elapsed = 820 ms>
18-03-27 13:12:12.491 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460465, txs = 440, result = IMPORTED_BEST, time elapsed = 1627 ms>
18-03-27 13:12:15.727 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460471, txs = 467, result = IMPORTED_BEST, time elapsed = 937 ms>
18-03-27 13:12:27.178 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460479, txs = 450, result = IMPORTED_BEST, time elapsed = 874 ms>
18-03-27 13:12:29.801 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460480, txs = 467, result = IMPORTED_BEST, time elapsed = 820 ms>
18-03-27 13:12:30.738 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460481, txs = 467, result = IMPORTED_BEST, time elapsed = 937 ms>
18-03-27 13:12:31.486 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460482, txs = 438, result = IMPORTED_BEST, time elapsed = 748 ms>
18-03-27 13:12:33.855 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460487, txs = 402, result = IMPORTED_BEST, time elapsed = 665 ms>
18-03-27 13:12:35.907 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460490, txs = 467, result = IMPORTED_BEST, time elapsed = 681 ms>
18-03-27 13:12:36.719 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460491, txs = 467, result = IMPORTED_BEST, time elapsed = 812 ms>
18-03-27 13:12:40.026 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460498, txs = 411, result = IMPORTED_BEST, time elapsed = 744 ms>
18-03-27 13:12:41.281 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460500, txs = 467, result = IMPORTED_BEST, time elapsed = 824 ms>
18-03-27 13:12:42.223 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460501, txs = 467, result = IMPORTED_BEST, time elapsed = 942 ms>
18-03-27 13:12:44.277 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460506, txs = 409, result = IMPORTED_BEST, time elapsed = 615 ms>
18-03-27 13:12:45.381 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460508, txs = 467, result = IMPORTED_BEST, time elapsed = 764 ms>
18-03-27 13:12:46.380 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460509, txs = 467, result = IMPORTED_BEST, time elapsed = 999 ms>
18-03-27 13:12:47.740 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460511, txs = 467, result = IMPORTED_BEST, time elapsed = 775 ms>
18-03-27 13:12:48.562 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460512, txs = 467, result = IMPORTED_BEST, time elapsed = 821 ms>
18-03-27 13:12:49.433 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460513, txs = 467, result = IMPORTED_BEST, time elapsed = 871 ms>
18-03-27 13:12:51.783 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460516, txs = 433, result = IMPORTED_BEST, time elapsed = 895 ms>
18-03-27 13:12:53.153 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460518, txs = 467, result = IMPORTED_BEST, time elapsed = 913 ms>
18-03-27 13:12:56.178 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460521, txs = 467, result = IMPORTED_BEST, time elapsed = 1355 ms>
18-03-27 13:12:57.162 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460522, txs = 467, result = IMPORTED_BEST, time elapsed = 984 ms>
18-03-27 13:12:58.291 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460524, txs = 467, result = IMPORTED_BEST, time elapsed = 763 ms>
18-03-27 13:12:59.164 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460525, txs = 467, result = IMPORTED_BEST, time elapsed = 873 ms>
18-03-27 13:13:00.576 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460528, txs = 467, result = IMPORTED_BEST, time elapsed = 599 ms>
18-03-27 13:13:02.483 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460530, txs = 467, result = IMPORTED_BEST, time elapsed = 886 ms>
18-03-27 13:13:03.780 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460531, txs = 467, result = IMPORTED_BEST, time elapsed = 1297 ms>
18-03-27 13:13:04.594 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460532, txs = 438, result = IMPORTED_BEST, time elapsed = 814 ms>
18-03-27 13:13:06.615 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460536, txs = 467, result = IMPORTED_BEST, time elapsed = 707 ms>
18-03-27 13:13:07.463 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460537, txs = 446, result = IMPORTED_BEST, time elapsed = 847 ms>
18-03-27 13:13:08.430 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460538, txs = 467, result = IMPORTED_BEST, time elapsed = 967 ms>
18-03-27 13:13:10.248 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460540, txs = 467, result = IMPORTED_BEST, time elapsed = 840 ms>
18-03-27 13:13:11.224 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460541, txs = 451, result = IMPORTED_BEST, time elapsed = 955 ms>
18-03-27 13:13:15.053 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460549, txs = 467, result = IMPORTED_BEST, time elapsed = 867 ms>
18-03-27 13:13:15.897 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460550, txs = 467, result = IMPORTED_BEST, time elapsed = 844 ms>
18-03-27 13:13:23.608 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460555, txs = 467, result = IMPORTED_BEST, time elapsed = 987 ms>
18-03-27 13:13:24.876 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460557, txs = 467, result = IMPORTED_BEST, time elapsed = 708 ms>
18-03-27 13:13:26.136 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460558, txs = 409, result = IMPORTED_BEST, time elapsed = 824 ms>
18-03-27 13:13:27.989 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460562, txs = 466, result = IMPORTED_BEST, time elapsed = 837 ms>
18-03-27 13:13:29.931 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460566, txs = 423, result = IMPORTED_BEST, time elapsed = 723 ms>
18-03-27 13:13:50.752 INFO  SYNC [sync-ib]: <import-status: node = d9242b, number = 460570, txs = 467, result = IMPORTED_BEST, time elapsed = 1627 ms>
18-03-27 13:13:53.181 INFO  SYNC [sync-ib]: <import-status: node = d9242b, number = 460572, txs = 467, result = IMPORTED_BEST, time elapsed = 1377 ms>
18-03-27 13:14:03.456 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460578, txs = 434, result = IMPORTED_BEST, time elapsed = 1232 ms>
18-03-27 13:14:04.742 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460579, txs = 467, result = IMPORTED_BEST, time elapsed = 1285 ms>
18-03-27 13:14:05.933 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460580, txs = 467, result = IMPORTED_BEST, time elapsed = 1190 ms>
18-03-27 13:14:22.211 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460584, txs = 467, result = IMPORTED_BEST, time elapsed = 1226 ms>
18-03-27 13:14:23.529 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460585, txs = 435, result = IMPORTED_BEST, time elapsed = 1317 ms>
18-03-27 13:14:33.476 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460590, txs = 467, result = IMPORTED_BEST, time elapsed = 1463 ms>
18-03-27 13:14:34.672 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460591, txs = 467, result = IMPORTED_BEST, time elapsed = 1196 ms>
18-03-27 13:14:36.141 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460592, txs = 467, result = IMPORTED_BEST, time elapsed = 1469 ms>
18-03-27 13:14:37.486 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460593, txs = 467, result = IMPORTED_BEST, time elapsed = 1345 ms>
18-03-27 13:14:39.014 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460594, txs = 467, result = IMPORTED_BEST, time elapsed = 1528 ms>
18-03-27 13:14:40.444 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460595, txs = 467, result = IMPORTED_BEST, time elapsed = 1429 ms>
18-03-27 13:14:41.567 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460596, txs = 467, result = IMPORTED_BEST, time elapsed = 1122 ms>
18-03-27 13:14:43.108 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460598, txs = 467, result = IMPORTED_BEST, time elapsed = 721 ms>
18-03-27 13:14:44.013 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460599, txs = 467, result = IMPORTED_BEST, time elapsed = 905 ms>
18-03-27 13:14:44.891 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460600, txs = 467, result = IMPORTED_BEST, time elapsed = 877 ms>
18-03-27 13:14:45.766 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460601, txs = 467, result = IMPORTED_BEST, time elapsed = 875 ms>
18-03-27 13:14:46.413 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460602, txs = 467, result = IMPORTED_BEST, time elapsed = 647 ms>
18-03-27 13:14:47.260 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460603, txs = 467, result = IMPORTED_BEST, time elapsed = 847 ms>
18-03-27 13:14:48.320 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460604, txs = 444, result = IMPORTED_BEST, time elapsed = 1060 ms>
18-03-27 13:14:57.619 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460607, txs = 450, result = IMPORTED_BEST, time elapsed = 1060 ms>
18-03-27 13:14:58.665 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460608, txs = 467, result = IMPORTED_BEST, time elapsed = 1046 ms>
18-03-27 13:15:07.648 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460614, txs = 437, result = IMPORTED_BEST, time elapsed = 1285 ms>
18-03-27 13:15:11.419 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460621, txs = 467, result = IMPORTED_BEST, time elapsed = 846 ms>
18-03-27 13:15:12.134 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460622, txs = 467, result = IMPORTED_BEST, time elapsed = 714 ms>
18-03-27 13:15:13.005 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460623, txs = 467, result = IMPORTED_BEST, time elapsed = 870 ms>
18-03-27 13:15:13.849 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460624, txs = 467, result = IMPORTED_BEST, time elapsed = 844 ms>
18-03-27 13:15:21.153 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460634, txs = 467, result = IMPORTED_BEST, time elapsed = 1134 ms>
18-03-27 13:15:22.617 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460636, txs = 467, result = IMPORTED_BEST, time elapsed = 953 ms>
18-03-27 13:15:23.333 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460637, txs = 467, result = IMPORTED_BEST, time elapsed = 716 ms>
18-03-27 13:15:24.056 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460638, txs = 467, result = IMPORTED_BEST, time elapsed = 723 ms>
18-03-27 13:15:24.678 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460639, txs = 467, result = IMPORTED_BEST, time elapsed = 621 ms>
18-03-27 13:15:31.241 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460653, txs = 467, result = IMPORTED_BEST, time elapsed = 900 ms>
18-03-27 13:15:32.125 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460654, txs = 467, result = IMPORTED_BEST, time elapsed = 883 ms>
18-03-27 13:15:34.843 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460658, txs = 413, result = IMPORTED_BEST, time elapsed = 887 ms>
18-03-27 13:15:36.122 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460660, txs = 467, result = IMPORTED_BEST, time elapsed = 644 ms>
18-03-27 13:15:38.373 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460663, txs = 460, result = IMPORTED_BEST, time elapsed = 740 ms>
18-03-27 13:15:39.547 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460665, txs = 467, result = IMPORTED_BEST, time elapsed = 916 ms>
18-03-27 13:15:44.528 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460668, txs = 467, result = IMPORTED_BEST, time elapsed = 918 ms>
18-03-27 13:15:47.081 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460674, txs = 467, result = IMPORTED_BEST, time elapsed = 784 ms>
18-03-27 13:15:48.578 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460675, txs = 419, result = IMPORTED_BEST, time elapsed = 937 ms>
18-03-27 13:15:50.622 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460679, txs = 467, result = IMPORTED_BEST, time elapsed = 948 ms>
18-03-27 13:15:52.268 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460680, txs = 467, result = IMPORTED_BEST, time elapsed = 759 ms>
18-03-27 13:15:52.949 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460681, txs = 467, result = IMPORTED_BEST, time elapsed = 681 ms>
18-03-27 13:15:56.601 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460684, txs = 467, result = IMPORTED_BEST, time elapsed = 1091 ms>
18-03-27 13:15:58.904 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460687, txs = 467, result = IMPORTED_BEST, time elapsed = 1121 ms>
18-03-27 13:16:00.101 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460688, txs = 467, result = IMPORTED_BEST, time elapsed = 1197 ms>
18-03-27 13:16:02.192 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460691, txs = 444, result = IMPORTED_BEST, time elapsed = 912 ms>
18-03-27 13:16:03.027 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460692, txs = 409, result = IMPORTED_BEST, time elapsed = 835 ms>
18-03-27 13:16:04.092 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460693, txs = 467, result = IMPORTED_BEST, time elapsed = 1065 ms>
18-03-27 13:16:07.610 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460696, txs = 467, result = IMPORTED_BEST, time elapsed = 1897 ms>
18-03-27 13:16:11.228 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460703, txs = 405, result = IMPORTED_BEST, time elapsed = 1307 ms>
18-03-27 13:16:12.172 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460704, txs = 467, result = IMPORTED_BEST, time elapsed = 944 ms>
18-03-27 13:16:14.721 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460706, txs = 467, result = IMPORTED_BEST, time elapsed = 1605 ms>
18-03-27 13:16:16.345 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460707, txs = 467, result = IMPORTED_BEST, time elapsed = 1623 ms>
18-03-27 13:16:17.381 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460708, txs = 467, result = IMPORTED_BEST, time elapsed = 1036 ms>
18-03-27 13:16:20.253 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460712, txs = 467, result = IMPORTED_BEST, time elapsed = 1182 ms>
18-03-27 13:16:21.254 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460713, txs = 467, result = IMPORTED_BEST, time elapsed = 1001 ms>
18-03-27 13:16:23.707 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460717, txs = 467, result = IMPORTED_BEST, time elapsed = 662 ms>
18-03-27 13:16:24.347 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460718, txs = 467, result = IMPORTED_BEST, time elapsed = 640 ms>
18-03-27 13:16:25.696 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460720, txs = 467, result = IMPORTED_BEST, time elapsed = 734 ms>
18-03-27 13:16:26.324 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460721, txs = 431, result = IMPORTED_BEST, time elapsed = 628 ms>
18-03-27 13:16:29.924 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460724, txs = 467, result = IMPORTED_BEST, time elapsed = 1173 ms>
18-03-27 13:16:32.167 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460725, txs = 467, result = IMPORTED_BEST, time elapsed = 2242 ms>
18-03-27 13:16:34.466 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460726, txs = 467, result = IMPORTED_BEST, time elapsed = 1422 ms>
18-03-27 13:16:35.378 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460727, txs = 467, result = IMPORTED_BEST, time elapsed = 912 ms>
18-03-27 13:16:37.732 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460729, txs = 467, result = IMPORTED_BEST, time elapsed = 1514 ms>
18-03-27 13:16:39.273 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460730, txs = 467, result = IMPORTED_BEST, time elapsed = 1541 ms>
18-03-27 13:16:40.603 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460731, txs = 467, result = IMPORTED_BEST, time elapsed = 1330 ms>
18-03-27 13:16:49.480 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460741, txs = 467, result = IMPORTED_BEST, time elapsed = 1059 ms>
18-03-27 13:16:50.423 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460742, txs = 407, result = IMPORTED_BEST, time elapsed = 943 ms>
18-03-27 13:16:52.944 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460744, txs = 467, result = IMPORTED_BEST, time elapsed = 821 ms>
18-03-27 13:16:53.990 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460745, txs = 467, result = IMPORTED_BEST, time elapsed = 1046 ms>
18-03-27 13:16:55.310 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460746, txs = 467, result = IMPORTED_BEST, time elapsed = 1320 ms>
18-03-27 13:16:56.346 INFO  SYNC [sync-ib]: <import-status: node = f9ea8c, number = 460747, txs = 467, result = IMPORTED_BEST, time elapsed = 1035 ms>`
