### ISSUE TITLE
Aion kernel error: BlockHeaderValidator

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [aionnetwork/aion#303]
Aion kernel error: 

18-03-28 19:35:32.448 ERROR SYNC [p2p-worker-4]: BlockHeaderValidator raised errors: 
AionPOWRule				computed output (56717148849279242159522091270045692399178294137847297360779114871993166993586) violates boundary condition (14854661864953969906808336755444247319213596493347089677929132008712396361)

Aion solo mining pool:

2018-03-28 19:35:18 [Pool]	[aion] (Thread 1) getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"connect ETIMEDOUT 127.0.0.1:8545"}

**Comment by AionJayT** [comment]
the issue happens during the header format change. the current version should not have this issue. close issue.
