### ISSUE TITLE
Kernel stops syncing but uses up a lot of resources

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion#330]
I've noticed that my kernel sometimes stops syncing after a while, while there are still connected peers. What's strange to me is that my PC gets very slow, as it's using up a lot of CPU power, while seemingly doing nothing. When restarting the kernel, the syncing starts back up again.

What's also strange (but might be unrelated) is that when closing the kernel, it hangs for a long time at `Shutting down DB...`.

**Comment by JimVanEeden** [comment]
One thing I've noticed is that it happens only when there are a lot of transactions in the blocks.

**Comment by yulongnuco** [comment]
It's probably due to heavy disk read/write when you're importing a block with tons of transactions. It takes up to seconds to import one such block.

**Comment by JimVanEeden** [comment]
Even if it is, it shouldn't be happening that the kernel just stops syncing after a while.

**Comment by AionJayT** [comment]
This issue happens may be due to the Level DB was doing the compaction. Will have an enhancement in the later version.

**Comment by AionJayT** [comment]
I think it has been fixed after the 0.3.2.1
