### ISSUE TITLE
OutOfMemoryError for "sync-ss" "pool-4-thread-3" "EpPS"

### ISSUE THREAD

**Issue by AlexandraRoatis** [aionnetwork/aion#345]
Version (0.1.18.806d8c0)[https://github.com/aionnetwork/aion/tree/806d8c081f9ea63fb44b3956807bf3f1782b9fef]

[hs_err_pid97075.log.zip](https://github.com/aionnetwork/aion/files/1878053/hs_err_pid97075.log.zip)
[nohup.out.zip](https://github.com/aionnetwork/aion/files/1878054/nohup.out.zip)

**Comment by AionJayT** [comment]
this issue has been fixed after version 0.2.
