### ISSUE TITLE
HttpServer logs out incorrect binding

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion#43]
In debug mode, the JSON-RPC api server will always indicate:
``18-02-27 16:36:11.542 DEBUG API  [main]: <rpc action=start bind=0.0.0.0:8545>``

From here:
https://github.com/aionnetwork/aion/blob/11dace25c39404c2238f71a782deb33ba44a8dc7/modApiServer/src/org/aion/api/server/http/HttpServer.java#L614-L615

**Comment by aion-6368726973** [comment]
patch at 9932ccae2a9ac02ba02f69b61718c2fac57302fe
