### ISSUE TITLE
jni.h Not Found

### ISSUE THREAD

**Issue by joesixpack** [aionnetwork/aion#431]
It is in $JAVA_HOME/include.

![image](https://user-images.githubusercontent.com/23145642/39022296-b6891692-43e9-11e8-926e-a3c0d6f94847.png)

**Comment by yulongaion** [comment]
Hi @joesixpack, you need to set the `JAVA_HOME` environment variable.

**Comment by joesixpack** [comment]
Already set.  All of it.

**Comment by joesixpack** [comment]
Problem seems to be in ModCrypto.jar as shown in screenshot above.

**Comment by joesixpack** [comment]
I've resolved the issue by upgrading to JDK 10 and/or the latest ant.
