### ISSUE TITLE
Acceptance of now invalid keystores

### ISSUE THREAD

**Issue by yao-sun** [aionnetwork/aion#458]
In the following example, a user (myself) is able to unlock a now "incorrect" keystore file using the API:

~~~~java
18-04-28 01:54:17.044 INFO  API  [main]: <rpc-server - started on 127.0.0.1:8545>
18-04-28 01:54:32.334 DEBUG API  [rpc-worker-1]: <request mth=[personal_unlockAccount] params=["0x272d91d7995f52d0259953ebc29ea209dd481ec4626e6e93835ede081a3ff548","","314159"]>
18-04-28 01:54:33.398 DEBUG API  [rpc-worker-1]: <unlock-success addr=272d91d7995f52d0259953ebc29ea209dd481ec4626e6e93835ede081a3ff548>
~~~~

We should handle this case properly, either by migrating the keystore file to its new address (functionality similar to import), or by throwing an error message. Note that this is still "valid" in the sense that the private key is successfully decrypted, but creates confusion as to the standard addressing format in AION.

This can be recreated by placing an old keystore format file on any Q1+ network

**Comment by AionJayT** [comment]
fix in https://github.com/aionnetwork/aion/pull/481
close the issue
