### ISSUE TITLE
Aion Seed Nodes Wiki - Incorrect Information

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion#483]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**:
> - **Which operating system?**:
> - **Which distributor and version?**:
> - **How installed?**:
> - **Are you fully synchronized?**:
> - **Did you try to restart the node?**:

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

* Navigate to this page: https://github.com/aionnetwork/aion/wiki/Aion-Seed-nodes

The seed nodes are still incorrect, let's ensure they list both the TestNet nodes and the MainNet (Kilimanjaro) nodes.

**Comment by AionJayT** [comment]
updated, close issue.
