### ISSUE TITLE
Silent Fail when running AION account creation under a no-console environment

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion#486]
> I'm running:
>
> - **Which Aion version?**: https://github.com/aionnetwork/aion/commit/c4f31463407d8a88c62ade310064daf230920ab7
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04.3 LTS
> - **How installed?**: source (IDEA)
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

In an IDE environment, there may not be a console available, when this happens System.console() will be null and our CLI will throw an NPE. I was able to recreate this behaviour by running the aion account creation command within IDEA. (Surprisingly this worked previously but no longer works).

At the very least we should be warning people by logging *something* out when we detect that there is no console environment available.

**Comment by AionJayT** [comment]
#494

**Comment by AionJayT** [comment]
issue fixed by #494
