### ISSUE TITLE
Add ability to pass a storage destination to the Keystore

### ISSUE THREAD

**Issue by centrys-otniel** [aionnetwork/aion#506]
The Keystore file has a hard-coded default storage path that is dependent on the working directory (i.e. where the java app was started).
`private static final String KEYSTORE_PATH = System.getProperty("user.dir") + "/keystore";`

It would be really helpful for the _aion_ui_ if we could create and list acoounts to/from a path given as a parameter. This way, we can keep all the configs and files in, say, _${**user.home**}/.aion_ directory

Alternatively there could be a custom property that we can set and use for the default path instead od _**user.dir**_

NOTE: This issue is resubmitted here afer a request from @qoire in https://github.com/aionnetwork/aion_ui/issues/46

**Comment by AionJayT** [comment]
@centrys-otniel Can your team implement this enhancement and submit a PR?

**Comment by centrys-otniel** [comment]
@AionJayT we made a PR for this - https://github.com/aionnetwork/aion/pull/516

let's talk on gitter if you have any concerns
