### ISSUE TITLE
[json-rpc api][feature request] Option to run with ssl-enabled

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion#510]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**: 0.2.7
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**: N/A
> - **Are you fully synchronized?**: N/A
> - **Did you try to restart the node?**: N/A

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Feature Request: 

Add a configuration option to run the json-rpc NanoHttpd server with ssl (user has to provide ssl certificate in a folder)

Implementaion details:
* Document that if they toggle this, they won't be able to access json-rpc over plain http
* Add configuration option for user to a) toggle ssl feature b) provide certificate path
* When loading up NanoHttpd, check if ssl-toggle enabled && valid certificate exists; if so, pass the certification along to NanoHttpd (https://github.com/NanoHttpd/nanohttpd/blob/d757ade973791fdd64f87601341cd7fb48e5b810/core/src/test/java/org/nanohttpd/junit/protocols/http/HttpSSLServerTest.java) 

Test:
* User can access json-rpc endpoints over https and not http when feature enabled
* Can successfully reject missing and bad jks keystores (we can delegate the rejecting of bad/missing keystores to nanohttpd, but we need to catch that particular exception correctly and tell the user a message like: "bad keystore, we expect jks  .." or "missing keystore file ...") (see https://github.com/NanoHttpd/nanohttpd/blob/63815b9a19c35d965465fa25028cd0a9a5fbcb40/core/src/main/java/org/nanohttpd/protocols/http/NanoHTTPD.java#L267)

**Comment by AionJayT** [comment]
merged in
https://github.com/aionnetwork/aion/pull/591
