### ISSUE TITLE
Json rpc embedded webserver - option to switch implementations. 

### ISSUE THREAD

**Issue by AionJayT** [aionnetwork/aion#519]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**: 0.2.7
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**: via binaries 
> - **Are you fully synchronized?**: N/A
> - **Did you try to restart the node?**: N/A

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Currently, the json-rpc api http service of the kernel is using nanoHttpd, should consider more production ready http service library such as Jetty, Jersey.

**Comment by ali-sharif** [comment]
Resolved by https://github.com/aionnetwork/aion/pull/557
