### ISSUE TITLE
hellp!send error !Error: invalid address

### ISSUE THREAD

**Issue by workboy** [aionnetwork/aion#534]
I tried to unlock my wallet and sent coins to binance.com, which unlocked smoothly, but in the process of sending, prompted Error: invalid address,why?

**Comment by Glyck** [comment]
Binance doesn't support the Aion mainnet coins yet. Currently, binance uses the ethereum based Aion ERC20 tokens, which is a different blockchain and different address length and format. Hence the error. 
Liquidity for mined aion coins will come with either the first exchange to list the mainnet aion, or with the token bridge.

**Comment by workboy** [comment]
Now, does the exchange support the AION main network?
