### ISSUE TITLE
Checksummed Addresses

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion#543]
Posting here because not sure where else to post, this would affect moreso our frontend utilities. But here's the proposed code:

https://github.com/aionnetwork/aion/commit/46b4c1fdcbda765db90349065d4f02be06793d2b

The idea is to go with the original Eth implementation, using each bit as a determination as to whether an alphabetical character should be capitalized or not. This can keep our hashes short (if we want we can event reduce this down to a MD5.

**Comment by qoire** [comment]
Another question is whether we want to include the ``0xA0`` header character in the checksum. I'm of the opinion that we won't be differentiating between ``0xa0`` and ``0xA0`` anyways, so its safe to include.

**Comment by qoire** [comment]
As for where this impacts our kernel, _it would be nice_ if our keystore could start generating files that had the checksummed addresses instead of regular ones, and _if_ we were to detect a checksummed address through (for example) a JSON-RPC call, we would verify the validity.

**Comment by tcrowe** [comment]
@qoire Thanks for your reply. I've ported this one to work with AION addresses in the js client: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-utils/src/index.js#L240

It will be in the aion_web3 PR in a few days.

It would help if you generate me 6 addreses and checksum addresses from the java client. I will include that in my test suite.

I got these addressess from the Conquest test net then I generated checksum addresses. To my best understanding it's correct. Hopefully we can work together to prove it.

```
0xa07c95cc8729a0503c5ad50eb37ec8a27cd22d65de3bb225982ec55201366920
0xA07C95cC8729a0503C5ad50eb37eC8a27cD22D65dE3BB225982Ec55201366920

0xa05a3889b106e75baa621b8cc719679a3dbdd799afac1ca6b42d03dc93a23687
0xa05A3889b106e75baA621b8cC719679a3dBdD799afac1ca6B42D03DC93A23687

0xa0229e43f4a040f9fa6b2ab2f2cccc066025117def3414e08edbe7aee8e61647
0xA0229E43f4a040F9fa6B2AB2F2Cccc066025117def3414E08EdbE7aeE8e61647

0xa0dd16394f16ea21c8b45c00b2e43850ae7e8f00fe54789ddd1881d33b21df0c
0xa0Dd16394f16Ea21C8B45C00b2E43850aE7E8f00fe54789ddD1881D33B21DF0C

0xa046cc48bcde4b0b2ce2dbefb318f3778946b6c0011f691ecc4025cc145a93d3
0xa046Cc48Bcde4B0B2CE2dbeFB318f3778946B6C0011F691ecc4025Cc145a93d3

0xa0e1cca4fe786118c0abb1fdf45c04e44354f971b25c04ed77ac46f13cae179a
0xA0e1CcA4fE786118c0abb1fdF45C04e44354f971B25C04ED77aC46f13CaE179a

0xa0b1b3f651990669c031866ec68a4debfece1d3ffb9015b2876eda2a9716160b
0xA0B1b3f651990669c031866ec68A4debfECe1d3fFb9015B2876EDa2A9716160b

0xa012123456789012345678901234567890123456789012345678901234567890
0xa012123456789012345678901234567890123456789012345678901234567890
```

**Comment by tcrowe** [comment]
I ran the tests on these addresses and found that my check-checksum function and checksum-address function are not a match with yours.

I'm not sure the solution. Either yours conforms to ethereums, aion web3 conforms to your calculation, or I just did it wrong.

You can advise me when there is time.

**Comment by tcrowe** [comment]
For reference, all 1000 checksum addresses above were validated through the JS client. Any JS client can take advantage of the checksum addresses in the future so the original concern about compatibility could be reduced.

A developer could do:

```js
let {toChecksumAddress, checkAddressChecksum} = require('aion-web3/src/utils')
let checksumAddress = toChecksumAddress(
  'a0cdf8dad48505c49e6917c3b425b3d9ef465a988dec9efd2410a4b782b7239d'
)
console.log(checksumAddress)
// 0xA0Cdf8DaD48505c49E6917C3B425b3d9eF465a988DeC9Efd2410A4B782B7239D
console.log(checkAddressChecksum(checksumAddress))
// true
```

https://github.com/tcrowe/aion_web3/blob/aion-web3-v1-transition/src/lib/accounts.js#L63

https://github.com/tcrowe/aion_web3/blob/aion-web3-v1-transition/test/unit/utils.js#L175
