### ISSUE TITLE
Additional byte in the "AionTransaction.value" field makes the incompatible RLP result with Ethereum standard.

### ISSUE THREAD

**Issue by wellshang** [aionnetwork/aion#576]
> I'm running:
>
> - **Which Aion version? : master
> - **Which operating system? : Linux
> - **Which distributor and version? : Ubuntu 16.04
> - **How installed? : from source
> - **Are you fully synchronized? : No
> - **Did you try to restart the node? : yes

We're working on a Rust version AION implementation based on Parity(https://github.com/paritytech/parity-ethereum). The following error is reported during the transaction validation when syncing the block #6995.

thread 'sync::synctests::decode_and_encode_transaction' panicked at 'Unexpected rlp error: RlpInvalidIndirection', libcore/result.rs:945:5

It indicates that the field "AionTransaction.value" should not started with 0x00.
Would you please help check why the additional byte "0x00" was introduced?

RLP info:
transaction_rlp: ["0x00", "0xa013e4c5c2d303640796fa70e0653b2202c151fd5bcad2ab3aba533f600d6574", "**0x00be29368e82f82080**", "0x", "0x00056aacf97aacf2", "0x07a120", "0x00000002540be400", "0x01", "0x0c83ebb9faf4e2757377443967a60c1af2cf0b5804df7b41c29d519d4790f51c37495c50220e4f5fdadeb7afc9dfd85df50bf9522a2135a5846220d0ea12d0f34a8f3d9f219da5a04436bd7a3d649182fabff4186ee7807b3ac74be8bf68f40b"]
F8A600A0A013E4C5C2D303640796FA70E0653B2202C151FD5BCAD2AB3ABA533F600D65748900BE29368E82F82080808800056AACF97AACF28307A1208800000002540BE40001B8600C83EBB9FAF4E2757377443967A60C1AF2CF0B5804DF7B41C29D519D4790F51C37495C50220E4F5FDADEB7AFC9DFD85DF50BF9522A2135A5846220D0EA12D0F34A8F3D9F219DA5A04436BD7A3D649182FABFF4186EE7807B3AC74BE8BF68F40B

Transaction info:
https://mainnet.aion.network/#/transaction/333676896fe9ee8544e57a5468f2edaafb4298049827663b2291a2152819bb49

**Comment by AionJayT** [comment]
@wellshang The current Aion Rlp is not fully compatible with Ethereum. You may need to the encoding implementation.
