### ISSUE TITLE
Rollback issues for JournalPruneDataSource

### ISSUE THREAD

**Issue by a312516552** [aionnetwork/aion#578]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**: 0.2.x.{git-revision}
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

The prune method in JournalPruneDataSource only rollback delete operations and part of put operations that insert a new key that isn't in database in fork block at same level. It doesn't rollback "update" put operations if the key is already in database. The following test case will show this problem. I wonder if it's by design?

    @Test
    public void pruningTest_wFork_onPastLevel3() {
        db.setPruneEnabled(true);

        // block b0
        db.put(k1, v1);
        db.storeBlockChanges(b0, 0);

        // block b1
        db.put(k1, v2);
        db.storeBlockChanges(b1, 1);

        // block b2 : same level as block b1
        db.put(k1, v3);
        db.storeBlockChanges(b2, 1);

        // block b3
        db.put(k6, v6);
        db.storeBlockChanges(b3, 2);

        assertThat(source_db.get(k1).get()).isEqualTo(v3);
        assertThat(source_db.get(k6).get()).isEqualTo(v6);

        // prune block b0
        db.prune(b0, 0);
        assertThat(source_db.keys().size()).isEqualTo(2);
        assertThat(source_db.get(k1).get()).isEqualTo(v3);

        // prune block b2 at level 1 
        db.prune(b1, 1);
        assertThat(source_db.keys().size()).isEqualTo(2);
        assertThat(source_db.get(k1).get()).isEqualTo(v2); **was v3**

        // prune block b3
        db.prune(b3, 2);
        assertThat(source_db.get(k1).get()).isEqualTo(v2);  **was v3**
        assertThat(source_db.get(k6).get()).isEqualTo(v6);
    }

**Comment by AionJayT** [comment]
Hi @a312516552, thanks for your report, we will check it. Do you have the git revision for your test case?
