### ISSUE TITLE
question for the "status" of a transaction receipt

### ISSUE THREAD

**Issue by fredericzha** [aionnetwork/aion#595]
Hi aion team,

> I'm running:
>
> - **Which Aion version?** 0.2.8.ef5df39c
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

I noticed that in the rpc response for **eth_getTransactionReceipt**, there is an attribute named **status** (please refer to modApiServer/src/org/aion/api/server/types/TxRecpt.java line 208) which shows if the receipt has any error, or in other words, if the corresponding transaction had any error when the kernel tried to put it into a block.
I wonder if this attribute is necessary because the current implementation for **eth_getTransactionReceipt** returns a receipt of a transaction only if it is included in a sealed block, which means this transaction must be valid with no error. This makes the attribute **status** always equals to 0x1. As far as I understand, an erroneous transaction is destroyed with its receipt, so there won't be any chance for the request **eth_getTransactionReceipt** to get a receipt with error (**status** equals to 0x0)?
Did I miss something? Would you please clarify in which situation this **status** can be meaningful?
Thanks in advance!

Fred

**Comment by qoire** [comment]
Hey, good first question! The answer is that there is a differentiator between when a transaction is ``rejected`` vs. ``failed``.

We define a failed transaction as one that has not modified any world state (if you imagine the world of Aion to be the set of accounts), but still exists on the blockchain. This is marked with ``0x0`` in the status field. There are indeed situations where the status can be ``0x0``. For example: when a transaction is not supplied with enough gas and goes OOG, its considered a failed transaction.

Take a gander here:

https://github.com/aionnetwork/aion/blob/87b660e32c7c4c7ae2031e07bb8f8baa804b1381/modVM/src/org/aion/vm/TransactionExecutor.java#L226-L247

For further details on what is considered rejected vs. failed.

**Comment by fredericzha** [comment]
Hi, qoire. Thanks for your explanation!
I close this ticket as the question is answered.
