### ISSUE TITLE
Crash when p2p discover is enabled

### ISSUE THREAD

**Issue by closerm** [aionnetwork/aion#605]
I'm running:
> - **Which Aion version?**: 0.3.0.fc9fd98
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**: via binaries 
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

When upgrading to the recently released v0.3.0 version of the Aion Kernel, I configured my node as I had with the prior release and experienced an almost instant crash. This was traced to a problem with the <discover> setting in the config.xml file. By disabling this setting, the kernel no longer crashed.

Actual behavior: crash when starting the Aion kernel
Expected behavior: no crash.

At the request of Jay, I replaced the v0.3.0 upnp libraries with the v0.2.8 libraries. They appear to run fine, so the problem appears to have been introduced in the v0.3.0 upnp libraries.

Crash output attached.
[hs_err_pid1302.log](https://github.com/aionnetwork/aion/files/2302584/hs_err_pid1302.log)

**Comment by AionJayT** [comment]
Thanks for the report. we replaced the library. Close this issue
