### ISSUE TITLE
Support the "import" feature for solidity contracts

### ISSUE THREAD

**Issue by iamyulong** [aionnetwork/aion#611]
I recently received multiple complaints about Aion not supporting the solidity `import` features, and have a strong feeling that it is a demanding requirement.

This is traditionally solved by compiling multiple solidity source files locally and sending the binary to kernel for deployment. However, this would be a bad experience for Aion developers because only Ubuntu 16.04 is officially supported and many developers are using other platforms for development and relying the Web3 API for compilation and deployments.

I suggest we revise our API server to support this feature, since it's fairly easy to implement:
- Allow web3 clients to upload multiple solidity source files, either as a file list or a single file containing concatenated source code;
- Put the source file(s) in a temp folder and ask the `solc` to compile;
- Return the results to client.

**Comment by lazaridiscom** [comment]
@AionJayT , I just hit on this problem.

You applied a label `enhancement`, but `import` is an essential feature, and thus its missing implementation in AION is essentially a `high-severity bug`.

I mean, how can someone write modular code and use libraries without an `import` statement?

**Comment by arajasek** [comment]
Fixed in PRs #781 and #819 .
