### ISSUE TITLE
Very high values when eth.estimateGas requested

### ISSUE THREAD

**Issue by gurdeepakjoshi** [aionnetwork/aion#642]
**Which Aion version?**: 0.3.1.46f09bac
**Which operating system?**: Linux 
**Which distributor and version?**: Ubuntu 16.04 LTS 64 bit
**How installed?**: binaries
**Are you fully synchronized?**: yes
 **Did you try to restart the node?**: yes

Actual Behaviour
- Launch aion node
- cd web3/
- node console.js
- aion-127.0.0.1:8545> eth.estimateGas({data: "0x000"})
13914991129094744000
It returns a very high estimate which makes the contract deployment infeasible.

Expected Behaviour
estimateGas should return realistic estimate such as 2000000

FYI
If you run same node locally (private) without syncing with external nodes then this issue doesn't occur. This issue is only occuring on fully synced node.

**Comment by qoire** [comment]
@AionJayT might be important for us to check that we can reproduce this.

From my side:

I was unable to reproduce this issue with a locally synced node (as suggested by Gurdeep). I also was informed by another colleague that it seemed to have to do with his keystore being placed in the keystore folder vs not. I tried this as well and was not able to reproduce the error.

**Comment by qoire** [comment]
@gurdeepakjoshi Just to be clear, when you say fully synced, are you referring to ``mainnet`` or ``mastery``?

**Comment by gurdeepakjoshi** [comment]
> @gurdeepakjoshi Just to be clear, when you say fully synced, are you referring to `mainnet` or `mastery`?

I meant mastery.

**Comment by arajasek** [comment]
I was able to reproduce this on mastery using both v0.3.0.17d0f332, as well as the latest dev. I did not need to sync to completion in order to reproduce the bug.

I stepped through the code, and it looks like the wonky behaviour is happening inside the VM. @AionJayT is following up with the VM team.

**Comment by yulongaion** [comment]
Quick fix would be updating the `AionTransaciton` constructor to not set the `from` variable.

Sine this issue won't affect consensus, put it at low-to-median priority.

**Comment by AionJayT** [comment]
some of the contract calls do need to verify the sender, therefore, I think the better solution is putting an address when the call doesn't have the sender address or just return an error in the API layer.

**Comment by yulongaion** [comment]
I saw the transaction is signed by a random address. If we don't set the `from` variable, the `getFrom()` method will decode the address from the signature.

**Comment by arajasek** [comment]
PR #646 adds the Zero Address if no address is provided, resolves the issue.
