### ISSUE TITLE
ZMQ settings in config.xml

### ISSUE THREAD

**Issue by blake2n** [aionnetwork/aion#644]
Which Aion version?: 0.3.1.dcaf9e82d044d558b0c4550c1e64064682685332
Which operating system?: Linux
Which distributor and version?: Ubuntu 16.04 & Ubuntu 18.x
How installed?: binaries from github
https://github.com/aionnetwork/aion/releases/download/v0.3.1/aion-v0.3.1.dcaf9e8-2018-08-30.tar.bz2
Are you fully synchronized? yes
Did you try to restart the node? yes

This is less an issue VS the fact there is no information is not in any documentation at this time.

I would like to disable block polling and enable ZMQ block notification to reduce daemon RPC load.
As example the following line may be added to miningcore in the "daemons": section of the JSON
"zmqBlockNotifySocket": "tcp://10.90.23.9:9999",

Could you provide the documentation to configure the ZMQ in the aion/config/config.xml so ZMQ can be used with miningcore, s-nomp, mpos or aionpool2.

Thank you!

**Comment by AionJayT** [comment]
@aionmine-help the zmq service is used for the Aion Java API connection. Therefore, the user needs to integrate the Java API into their current service.
please check the docs first
https://docs.aion.network/docs/apis
https://docs.aion.network/docs/api-interaction-examples
