### ISSUE TITLE
Do not catch `Throwable`

### ISSUE THREAD

**Issue by yulongaion** [aionnetwork/aion#645]
`Throwable` is being caught in various places in the code base. This is quite dangerous imo because it stops both exceptions and errors from propagating to callers/thread. For most of the errors, they're beyond our capability of handling it, for instance linkage error or out of memory.

I'd suggest we replace it with `Exception` unless we're 100% sure JVM errors are properly considered.

**Comment by arajasek** [comment]
Solved in PR #684
