### ISSUE TITLE
Non-standard RLP encoding?

### ISSUE THREAD

**Issue by iamyulong** [aionnetwork/aion#680]
During the compatibility test between our Java and Rust kernels, I realized that the RLP encoding of long integers is not following the RLP specification.

https://github.com/aionnetwork/aion/blob/843761824132b2dfe2a6e8dbc5b755167f571718/modRlp/src/org/aion/rlp/RLP.java#L501-L513

The above `encodeLong()` method is widely used in the `AionTransaction` class.

For integers between `[0x00000000ffffffff, 0xffffffffffffffff]`, the encoding will contain up to four leading zeros. This will lead to inconsistent number encoding.

```
short -> int -> long -> BigInteger
                 |
         (extra zero bytes)
```

On side effect we've got so far is that extra logic will be required for numbers in the mentioned range in the rust kernel.

Also, need to double check if our offline signing tool has the correct implementation.

@AlexandraRoatis could help review this?

**Comment by AionJayT** [comment]
@yulongaion Yes, that's confirmed. For the long encode, we use different implement logic

**Comment by AlexandraRoatis** [comment]
The tests I added [here](https://github.com/aionnetwork/aion/blob/843761824132b2dfe2a6e8dbc5b755167f571718/modRlp/test/org/aion/rlp/RLPSpecExtraTest.java#L163-L239) check for the range where we differ. Note that only the `encodeLong()` functionality used in transactions has this behavior.
