### ISSUE TITLE
Can we reduce the default transaction nrg limit?

### ISSUE THREAD

**Issue by yulongaion** [aionnetwork/aion#689]
If a user does not specify the nrg limit when sending a transaction via web3, the default nrg limit will be `2,000,000`. This means the balance of the sender account has to be more than `2,000,000 NRG * 10,000,000,000 PLAT/NRG = 0.2 AION`. 

Can we reduce the default nrg limit? The current setup may cause unnecessary inconvenience when sending transaction from low-balance account. `go-ethereum` is taking the value of `90,000`, https://github.com/ethereum/go-ethereum/blob/f08f596a378e1bc0cfcb476868767b1f1d602c17/internal/ethapi/api.go#L1200

P.S. Chris found this issue when supporting an exchange.

**Comment by AionJayT** [comment]
@yulongaion I have no opinion about this. should we use the same value as the default?

**Comment by yulongaion** [comment]
I'd rather we go with a similar value as Ethereum.

**Comment by qoire** [comment]
Does this make it into our next release, seems like an easy but nice to have fix
