### ISSUE TITLE
Audit usage of Guava cache 

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion#698]
@AlexandraRoatis discovered an issue with the guava chache persisting to disk in low-memory-available situations (which still happens). It was discovered to be causing ugly race conditions with data retrieval from the database. 

The guava cache is still being used, primarily in the json rpc api implementation. 

Can we investigate: 
1) https://github.com/ben-manes/caffeine as a replacement to guava cache
2) conditions / known bugs under which guava would store cache-set to disk

The outcome here would be to have enough confidence in either a new release of Guava cache or Caffeine cache to re-enable the application-level caching features for the database layer.

**Comment by arajasek** [comment]
PR #699 switches us to the Caffeine library for Web3
