### ISSUE TITLE
eth_getTransactionByHash，"result": null；help me

### ISSUE THREAD

**Issue by Sayplaydiv** [aionnetwork/aion#706]
I transferred all the balances to another account and returned the transaction hash normally. But when I queried the transaction information through eth_getTransactionByHash, can I help me?

**Comment by AionJayT** [comment]
@Sayplaydiv Hi, could you submit the issue using the template?
 usually, this scenario could happen the transaction still pending in the transaction pool or transaction has been dropped by the pool. Could you give us more details? 
@arajasek could you keep tracking the issue?

**Comment by arajasek** [comment]
Hi @Sayplaydiv, I'm happy to help with this! In addition to what Jay mentioned, if you can provide the Transaction Hash in this case, that would help us help you :)
