### ISSUE TITLE
Web3 getBlock, getWork, transactionLog issues

### ISSUE THREAD

**Issue by nuco-shidokht** [aionnetwork/aion#74]
- boolean `fullTransactions = Boolean.parseBoolean((String) params.get(1));` throws an exception because it cannot convert types.
boolean` fullTransactions = Boolean.parseBoolean(params.get(1) + "");` works.

- When the boolean value is set to true `(eth.getBlock('blk_hash', true))`, blockToJson throws NullPointerException, because transaction is not 'contract creation' and contract address is set to Null in `jsonTx.put("address", TypeConverter.toJsonHex(_tx.getContractAddress().toString()));`
Also some fields required in Web3 formatting are missing.

- `eth_getWork` returns a byte array instead of the hash value.

- blockNumber, transactionIndex, logIndex fields are missing in transaction logs.

Corrections are in _api-dev_ branch.

**Comment by ali-sharif** [comment]
resolution available in https://github.com/aionnetwork/aion/pull/75

**Comment by ali-sharif** [comment]
Fixed by PR https://github.com/aionnetwork/aion/pull/75
