### ISSUE TITLE
[PROJECT] Root Directory is Overwhelming

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/aion#770]
What is the rationale of having the modules all in the root, instead of keeping them within a "mod" or "module" folder?

(Asking mainly because the AION project has an exceptional quality, compared to other BC related projects)

**Comment by AionJayT** [comment]
@lazaridiscom thanks for your opinion, we realize the issues you mentioned. Right now we have a plan to separate these modules into the independent projects. Means the devs can dedicate in some specific modules (projects) for increasing the dev speed.
