### ISSUE TITLE
[DOCS] Annoying Popup Text "The EU is stupid"

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/aion#777]
> The EU is stupid and requires all websites to have this silly cookie thing. By clicking on the button below, you accept that we'll place cookies on your computer. Shocking, I know. 

source: a pop-up on https://aiondocs.netlify.com/en/kernel/

A teach-in to a complex system like AION is difficult enough. The documentation should not distract, should not annoy, should not get political, patronizing etc. - those are standard-requirements which no one should discuss.

"The EU is stupid" - this is really redundant and should be removed. Bluntly, it makes a totally unprofessional impression (and I got a very positive impression from AION till now).

**Comment by AlexandraRoatis** [comment]
Thank you for the feedback. @mohnjatthews who manages our [docs repository](https://github.com/aionnetwork/docs) will address this issue.

**Comment by lazaridiscom** [comment]
Note that there is the possibility that this popup comes from the host (netlify.com).

As a sidenote:

your current doc site https://docs.aion.network/docs has a better look&feel (with the exception of the far too low contrast) than the one on netlify.com you plan to introduce. Possibly reconsider the migration.

**Comment by mohnjatthews** [comment]
Thanks for the feedback @lazaridiscom! The cookie notification has to something more production suitable.

If you've got the time, I'd really appreciate it if you could go into more detail on why you prefer the [current docs site](https://docs.aion.network/docs) design? Is there anything that stands out?

**Comment by lazaridiscom** [comment]
> If you've got the time, I'd really appreciate it if you could go into more detail

here we go:

* the design looks far more professional
* the navigation responds better (fluent etc.)
* has an own domain
* Editing can be done without github workflow (which is many times just too much for documentation)

The one negative thing of the current site:

* low contrast (something that is quasi-forbidden for documentation)

> Also, if you've got issues with the docs, you can raise them directly on the Aion Docs repo.

You monitor all the repos? (on many projects, there are long delays on the doc repositories)

**Comment by mohnjatthews** [comment]
That's great, thanks for your help @lazaridiscom. We've had a few contributors complain about having to create an account on Readme.io in order to contribute to the current documentation site, so we built this one to explore how we could do things differently.

We're going to tweaking the design of the new docs site over the next few weeks, and obviously if the beta doesn't perform well then we'll stick with the current solution :)

**Comment by lazaridiscom** [comment]
Well, I would have complained, too - I just happened to have already an account there at reame.io.

This setup would be close to ideal:

* OAuth login to reame.io via github credentials
  * I can use the readme.io UI to edit
* I can use a repository and the github-workflow to edit

Kind of a `[Edit on readme.io] - [Edit on github]` - thus everyone is happy.

Sadly, the tools out there do not have always the functionality/quality they should.

**Comment by lazaridiscom** [comment]
(btw: github has a new functionality "move issues", so you could move this issue over to the doc repo. Curious if this works...)

**Comment by lazaridiscom** [comment]
The new popup:

> The EU requires all websites to notify their users when cookies are in use. So that's what we're doing, we're telling you that we use cookies. Interestingly, a cookie was used to display this message. Learn more

Much better!

Thank your for your fast response.

**Comment by lazaridiscom** [comment]
strange, I could swear this was corrected. "EU is stupid" is back, please check.

**Comment by mohnjatthews** [comment]
Good catch. The cookie notification wasn't pushed to other branches. Should be fixed now.

**Comment by lazaridiscom** [comment]
All good!

Oh, and as a sidenote: personally, I permanently yell at the EU, as I'm highly annoyed by those popups etc.! "stupid" is the calmes tword I use...

But you get it: it's one thing what we do personally, it's another thing what we expose within docs to the public.
