### ISSUE TITLE
[PROJECT] Specify Documentation Requirements

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/aion#783]
## Problem 

The documentation is partially far too casual and becomes sometimes distracting or even annoying.

## Solution

Specify Documentation Requirements and stick to them, e.g.:

* Requirements for a README
  * Provides a Compact Intro
  * Provides Build-Test-Install-Start instructions
    * Points to the User/Developer Manual for further information
  * Provides ...

* Requirements for a Developer Manual
  * One and Only authoritative documentation
  * Keep tenor strictly technical (e.g. avoid jokes, smileys)
  * Do not explain things like `git clone` or a `cd aion-kernel`

* Requirements for End-User Documentation (e.g. Wallet)
  * ...

## Existent Guidelines

https://docs.aion.network/page/voice-guidelines

The existent guidelines could(!) be valid for "Marketing Material addressing Casual Folks". They are not valid for "Technical Material addressing Core-Developers" or "General Material addressing Evaluators".

Thus the Guidelines need to be revised, e.g. "Core Level Development" need a different set of guidelines, "Marketing on Twitter etc." a different one.

It would be helpful to specify first the target-audience:

(exaggerating a little bit here to make the point)

* Do you target super-young folks (even teenagers) which you want to bring on the platform?
* Do you target Evaluators, which evaluate multiple platforms in exhausting sessions, in order to find "the one" the use.
* Do you target ???

(etc.)

**Comment by AionJayT** [comment]
Thanks for your suggestion. But I think this issue does not belong to this repo (the aion kernel java implementation). I will forward it to the other place.
