### ISSUE TITLE
[PROJECT] Provide a "CREDITS.md" in root-dir

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/aion#784]
I noticed this document here:

https://github.com/aionnetwork/aion/wiki/Contributors

which is very friendly.

It would have more effect if the content would be placed within the root of the source tree, within a file `CREDITS.md`.

Would show that AION cares about giving credit where credit is due.

**Comment by AionJayT** [comment]
Due to the license change. We already put the contributor's list in the other branch.
https://github.com/aionnetwork/aion/blob/master-pre-merge/CONTRIBUTORS.md
Close these issue.
