### ISSUE TITLE
[WEBSITE] - fade-in effect annoying

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/aion#785]
(Issues like this would be filed -lack of a dedicated website repository-  within an "aion-platform" repo, see #776)

The AION website (https://aion.network) has a main weakness:

* The "Fade-In" Effect is highly annoying, especially when trying to read through the material quickly

## Suggestion

* Remove the fade-in effect completely, thus readers can read through quicker.

**Comment by AionJayT** [comment]
@lazaridiscom I think this issue is not related to this repo, I will forward it to the correct place. Close the issue.
