### ISSUE TITLE
[WIKI] Remove duplicate Information from wiki

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/aion#788]
## Problem

The documentation of the overall AION Platform is sometimes duplicated, here an example:

https://docs.aion.network/docs/migrating-smart-contracts-from-ethereum

https://github.com/aionnetwork/aion/wiki/Migrating-from-Ethereum

Hitting on duplicated information can be very annoying.

## Solution

* Remove everything that is contained in the docs from the wiki.
* Ideally: remove the wiki as a whole.

**Comment by AlexandraRoatis** [comment]
For official information please read at the official docs: https://docs.aion.network/
The GitHub wiki is of use internally for developers. 
Tasks for cleaning up the wiki fall under the category of bikeshedding.

**Comment by lazaridiscom** [comment]
> For official information please read at the official docs: https://docs.aion.network/

Why do you feel the need to write me this? My issue affects this documentation and the redundant duplicated information i imentioned.

> The GitHub wiki is of use internally for developers.

this is not an "internal" wiki, it is a public(!) wiki of a public(!) repo, and thus relevant(!) information which e.g. any evaluator will look at.

> Tasks for cleaning up the wiki fall under the category of bikeshedding.

This is not about "cleaning up the wiki", but about "cleaning up a bad situation around the AION documentation, which leads to a negative developer experience, and can have a negative impact on adoption".

Please reopen this issue.
