### ISSUE TITLE
[PROJECT] Revise the Issue-Tracking Process

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/aion#790]
Some documentation mentions AIONs "Engineering Excellence".

Other parts of the documentation mention ask for "Community Engagement", for "Contributions".

But here is the 

## Problem

Delayed response-times on project resources can have a highly demotivating effect. Additionally, the public repositories are part of the Engineering Process.

In order to have an "Excellent" Engineering Process, the Issue-Tracking must become a bit faster:

* **24h Initial response** time (e.g. assigning a label and assigning a team-member to the issue).

-

(for me this will be the last issue here. I saw that AION team-members are active on other resources, but at the same time the repositories here feel like dead. Please be aware that this makes a highly negative impression.)

**Comment by AionJayT** [comment]
@lazaridiscom The devs in the current repo are busying for the AVM integration and other stuff. Sorry for the late response.

**Comment by lazaridiscom** [comment]
@AionJayT (@aionjay)

> The devs in the current repo are busying for the AVM integration and other stuff. Sorry for the late response.

So why do you close the issue? The Process needs still

a) To be revised
b) To be publically documented (open project)

@AlexandraRoatis 
> All new issues are read daily. Our promptness in answering issues is correlated directly with the utility of the issue. This repository concerns coding tasks and kernel functionality. For reporting issues regarding the docs or website please use the specific repository opened for documentation.

You just confirmed that the Issue-Tracking-Process needs a revision

## Example

(e.g. "Never leave the  issue you read without a user-visible response, even if it is just placing a label "triage", thus another member can go on with assessing the issue. Even if you classify the issue as "useless", ensure that you at minimum label it for "triage").

-

Can one of you please reopen the issue? See, me not your enemy. My interest is that core-developers can produce core-code in peace, whilst the project-resources are kept active and people an encouraged to contribute.
