### ISSUE TITLE
Static Sonar scan checks found a decent amount of bugs on the master source.

### ISSUE THREAD

**Issue by bpetridis** [aionnetwork/aion#797]
Hi Good people at AION.

Ran a sonar static scan over the source of the master branch on a slightly older commit now. Version v0.3.2.1, scanning environment was windows, java 1.8.0_191. Excluded any test source files from the scan. It did find a lot of issues. The remediation effort isn't that major though. Thought I'd raise this to give you guys a chance to take a look and I'll follow this so if you get a chance to rectify some, please let me know and I'll happily scan it again. Have a Jenkins job setup to do it, recommended fixes are in line on the issues tab.

https://sonarcloud.io/dashboard?id=AION-Network

Cheers

Bill :-)

**Comment by AlexandraRoatis** [comment]
Thank you for the submission! We have seen a similar report in #766. Most of these issues are false alarms relating to coding style more than to faults in logic. However, the kernel will undergo some refactoring in the next weeks and we'll handle some of these issues as well.

**Comment by lazaridiscom** [comment]
Sonarcloud feels to me like a "useful toy which tries too much to impress".

**Comment by bpetridis** [comment]
> Sonarcloud feels to me like a "useful toy which tries too much to impress".

Has helped my projects in the past especially when our heap utilisation was maxing out. Yes not everything it picks up is worth actioning, but things like dupes etc are worth ironing out. Either way it's something I thought the team might want to take a look at. It's just there to help.

**Comment by lazaridiscom** [comment]
"Tools" help, "Toys" distract.

I guess the team could assess the tool/toy status by looking at the reported "critical/blocker" bugs:

https://sonarcloud.io/project/issues?id=AION-Network&resolved=false&severities=BLOCKER%2CCRITICAL&types=BUG

which should be fixed anyways, if really that critical.

**Comment by AionJayT** [comment]
Checked all the issues, I am pretty sure these are a false alarm. Also, most of the alarm reported in the testing classes. I picked 3 issues might have the concern and fix it in the #824

**Comment by bpetridis** [comment]
Cool - FYI re-scanned and adjusted the exclusion clauses to pickup the test java files, had the case wrong before - scanning out much nicer now  https://sonarcloud.io/dashboard?id=AION-Network
