### ISSUE TITLE
Synced node throwing an error 

### ISSUE THREAD

**Issue by dipeshnuco** [aionnetwork/aion#835]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**: 0.2.x.{git-revision}
      Aion Java Kernel v0.3.2.1
> - **Which operating system?**: Linux
      Linux
> - **Which distributor and version?**: Ubuntu 16.04
      16.04
 - **How installed?**: via binaries / from source
  Binary
> - **Are you fully synchronized?**: no / yes
Yes
> - **Did you try to restart the node?**: no / yes
No

19-02-21 16:31:25.201 ERROR EXE  [msg-eq]: exception [Invalid argument].
19-02-21 16:31:25.201 ERROR EXE  [msg-eq]: feSocket.disconnect failed, probably due to forceful context close [Invalid argument].
19-02-21 16:31:25.201 INFO  EXE  [msg-eq]: socket disconnected!
19-02-21 16:31:28.164 ERROR BSE  [api]: [connect] Connect failed.
AION: Connecting to...127.0.0.1:8547
AION: API Connection could not be established.
19-02-21 16:31:31.168 ERROR BSE  [api]: [destroyApi]API not initialized yet!
AION: Unlock Call: 
AION: Unlock: java.lang.NullPointerException
AION: Minting
AION: Exception: java.lang.NullPointerException

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by AionJayT** [comment]
@dipeshnuco could we get more details like the configs on both sides? Also, how does it happen, is it failed at the beginning of works in the beginning and then failed later.

**Comment by AionJayT** [comment]
Close issue because of no following response.
