### ISSUE TITLE
Paths for config files are confusing

### ISSUE THREAD

**Issue by arajasek** [aionnetwork/aion#896]
## Description

We have 2 paths where config files exist. If I understand them correctly, they are as follows:
1. \<network\>/config/ contains the config files that are loaded at startup. 
2. config/\<network\> contains the default config and genesis for each of the networks. If the path in 1. doesn't exist, these files are copied into that folder.

This is rather confusing, and has led to many people losing a few hours wondering what's wrong, because they're changing info in a config file, but not seeing the expected change in behaviour. 

I'm not sure what the best resolution is, but it might be as simple as renaming the existing aion/config/ folder to something like aion/defaults/.

**Comment by AionJayT** [comment]
The config instruction is here!
https://docs.aion.network/docs/configure

But if a lot of people complain about the config issue, then we can rename the `config` folder.

**Comment by AlexandraRoatis** [comment]
also, at kernel start, the config paths are listed in the logs

**Comment by iamyulong** [comment]
If the only purpose of the config/<network> folder is to store the default configurations, why not put them into the resources (which compiles into the jars)? 

Unless we're expecting the users to copy config files manually and then customize it.
