### ISSUE TITLE
Where do i find the peermagic value, normally its in chainparams.cpp

### ISSUE THREAD

**Issue by g00dnatur3** [aionnetwork/aion#898]
Hi,

I'm trying to use p2p for block notification on the mainnet, where do i find the peerMagic value..

Normally i look in the chainparams.cpp, but since this is a new java implementation im lost..

Little help would be much obliged

**Comment by AionJayT** [comment]
Hi @g00dnatur3,
Can you describe more details about the peerMagic value? 
For the Aion Java kernel p2p implement details, you can look from these 3 classes 
P2pMgr
https://github.com/aionnetwork/aion/blob/master/modP2pImpl/src/org/aion/p2p/impl1/P2pMgr.java
NodeMgr
https://github.com/aionnetwork/aion/blob/master/modP2pImpl/src/org/aion/p2p/impl/comm/NodeMgr.java
PeerMetric
https://github.com/aionnetwork/aion/blob/master/modP2pImpl/src/org/aion/p2p/impl/comm/PeerMetric.java

**Comment by g00dnatur3** [comment]
Hi, thank you for responding.

Please look here:

`https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp`

My understanding is the `peerMagic` value is used to make anonymous p2p handshakes for the purpose of getting a block notification without having to poll the daemon.. its vastly more efficient.

Look here, starting at line 104:
```
        pchMessageStart[0] = 0xf9;
        pchMessageStart[1] = 0xbe;
        pchMessageStart[2] = 0xb4;
        pchMessageStart[3] = 0xd9;
```
This is the `peerMagic` value for the bitcoin mainnet, we know its the mainnet cause one line down we see the bitcoin mainnet port: `8333`

in nomp, when you configure a coin to support p2p connections you would put inside the coin config json:
```
{
   "peerMagic": "f9beb4d9"
}
```

This would allow you to enable p2p connections in the pool config file...

I have not read deeper in the nomp code or the bitcoin code to understand better how this value is used...

But i assume its some header values used during the p2p handshaking process...

Hope that clarifies what exactly im looking for.

Cheers

**Comment by AionJayT** [comment]
Hi,
Current Aion P2p handshake spec you can find it within this page
https://github.com/aionnetwork/aion/wiki/Aion-P2p-Specifications
And for the message implementation, you can look into there:
https://github.com/aionnetwork/aion/tree/master/modP2pImpl/src/org/aion/p2p/impl/zero/msg
