### ISSUE TITLE
Syncing with nodes out of sync?

### ISSUE THREAD

**Issue by saaperezru** [aionnetwork/aion#90]
While updating to v13 in one of my nodes somenthing weird happened. I used the database I had in v12, which was almost up to date, then the v13 started syncing just fine for a while:

```
    DEBUG SYNC [sync-import]: <try-import-block num=266113 hash=d5c851 parent=c39e81>
    INFO  SYNC [sync-import]: <import-best num=266113 hash=d5c851 txs=0>
    DEBUG SYNC [sync-import]: <try-import-block num=266114 hash=029168 parent=d5c851>
    INFO  SYNC [sync-import]: <import-best num=266114 hash=029168 txs=0>
```

But then at some point it started failing all of a sudden:

```
    ERROR SYNC [p2p-write]: <res-bodies decode-msg>
    DEBUG SYNC [p2p-write]: <res-bodies bodies=321 from-node=0466a7>
    DEBUG SYNC [p2p-write]: <validate-incoming-blocks size=321 from=265877 to=266197>
    DEBUG SYNC [sync-import]: <try-import-block num=265877 hash=fcb880 parent=436f5b>
    DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=265877 hash=fcb880>
    DEBUG SYNC [sync-import]: <try-import-block num=265878 hash=1c4293 parent=fcb880>
    DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=265878 hash=1c4293>
```

The only way I find to explain this is that my node started to sync with another peer with off-chain blocks and got off-chain as well, then it tried to sync with an on-chain node and could not move forward. Is somenthing like this possible?

**Comment by MrYukonC** [comment]
I can confirm that this behavior is also happening to me.  However, it even happens when the only peers it's connected to are all up to date.

**Comment by gonuco** [comment]
the upcoming release ( v0.1.14,  Mar 5, Monday)  will help fix this issue by bring better stable syncing.  but incase you on sidechain,  you need ./aion.sh -r  block_number to revert your sidechain back.
