### ISSUE TITLE
Aion Java Kernel v0.4.0.2: Startup error (config-xml)

### ISSUE THREAD

**Issue by knaickerF9** [aionnetwork/aion#910]
Hi, I'm getting the following error when launching a branch new node:

<error on-parsing-config-xml msg=ParseError at [row,col]:[1,1]
Message: Premature end of file.>

    Which Aion version?: v0.4.0.2
    Which operating system?: Linux
    Which distributor and version?: Ubuntu 18.04 LTS
    How installed?: via binaries / aion-v0.4.0.2.092068b-2019-06-12.tar.bz2
    Are you fully synchronized?: no
    Did you try to restart the node?: no

**Comment by AionJayT** [comment]
Hi, I suspect your config settings have a format issue. Could you clean up the settings and execute the launch script again? or give us your XML files.  Thanks.
