### ISSUE TITLE
Module slf4j.simple not found, required by org.aion.avm.core

### ISSUE THREAD

**Issue by iamyulong** [aionnetwork/aion#911]
I was unable to run the `org.aion.Aion` class from the `modBoot`, after importing the project into IntelliJ IDEA. It seems that `slf4j.simple` is required by AVM but missing. 

Had no issues with building the project.

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module slf4j.simple not found, required by org.aion.avm.core

Process finished with exit code 1
```

**Comment by AionJayT** [comment]
This issue happens due to slf4j.simple lib has a conflict with logback-classic lib when kernel is loading the libs. Right now the easy way to avoid this issue is to build the avm jar without  slf4j.simple dependency (comment out the slf4j.simple in the module-info of the avm projects)

**Comment by AionJayT** [comment]
Will fix it when the kernel refactors the log system.

**Comment by rohitsahu21** [comment]
`Error`
