### ISSUE TITLE
sync-import thread need have higher priority then p2p thread.

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#99]
when tested on a quad core ,
the bandwidth can reach few MB/s.

![image](https://user-images.githubusercontent.com/35697444/36939220-5c003a7e-1efb-11e8-8edd-d30edd82f30c.png)

but the issue is if p2p thread use all cores ( 99% here ),  the sync-import thread will have no chance to write block into db.

![image](https://user-images.githubusercontent.com/35697444/36939241-8e81c3d2-1efb-11e8-9f41-a1ef6fc4903e.png)

**Comment by aion-6368726973** [comment]
I am closing this ticket due to p2p has been refactored.
